export const INIT_APP = 'INIT_APP';

export const SET_TOKEN = 'SET_TOKEN';

export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const AUTHENTICATING = 'AUTHENTICATING';
export const LOG_OUT = 'LOG_OUT';

export const UNLOCK_FILE = 'UNLOCK_FILE';

export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const REQUEST_UPDATE_UI = 'REQUEST_UPDATE_UI';
