export const INIT_APP = 'INIT_APP';

export const SET_TOKEN = 'SET_TOKEN';

export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const AUTHENTICATING = 'AUTHENTICATING';
export const LOG_OUT = 'LOG_OUT';

export const UNLOCK_FILE = 'UNLOCK_FILE';

export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const REQUEST_UPDATE_UI = 'REQUEST_UPDATE_UI';

/*
addProductToStock
*/

export const SET_COMPANY_FOR_PRODUCT = 'SET_COMPANY_FOR_PRODUCT';
export const SET_DISTRIBUTOR_FOR_PRODUCT = 'SET_DISTRIBUTOR_FOR_PRODUCT';
export const SET_CATEGORY_FOR_PRODUCT = 'SET_CATEGORY_FOR_PRODUCT';
export const SET_PRODUCT_FIELD = 'SET_PRODUCT_FIELD';
export const SAVING_PRODUCT = 'SAVING_PRODUCT';
export const SAVED_PRODUCT = 'SAVED_PRODUCT';
export const SAVED_PRODUCT_FAILED = 'SAVED_PRODUCT_FAILED';
